// <auto-generated />
using System;
using Kwetter.Services.FollowService.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kwetter.Services.FollowService.API.Infrastructure.Migrations
{
    [DbContext(typeof(FollowDbContext))]
    partial class FollowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Kwetter.Services.FollowService.API.Domain.Follow", b =>
                {
                    b.Property<Guid>("FollowingId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FollowDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FollowingId", "FollowerId");

                    b.HasIndex("FollowerId");

                    b.ToTable("Follow");
                });

            modelBuilder.Entity("Kwetter.Services.FollowService.API.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kwetter.Services.FollowService.API.Domain.Follow", b =>
                {
                    b.HasOne("Kwetter.Services.FollowService.API.Domain.User", "Follower")
                        .WithMany("Followings")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kwetter.Services.FollowService.API.Domain.User", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("Kwetter.Services.FollowService.API.Domain.User", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Followings");
                });
#pragma warning restore 612, 618
        }
    }
}
