// <auto-generated />
using System;
using Kwetter.Services.KweetService.API.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kwetter.Services.KweetService.API.DataAccess.Migrations
{
    [DbContext(typeof(KweetDbContext))]
    [Migration("20210419133352_KweetWithLikes")]
    partial class KweetWithLikes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Kwetter.Services.KweetService.API.Models.Kweet", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.ToTable("Kweets");
                });

            modelBuilder.Entity("Kwetter.Services.KweetService.API.Models.KweetLike", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("KweetId")
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("LikedDateTime")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("KweetId");

                    b.ToTable("KweetLike");
                });

            modelBuilder.Entity("Kwetter.Services.KweetService.API.Models.KweetLike", b =>
                {
                    b.HasOne("Kwetter.Services.KweetService.API.Models.Kweet", "Kweet")
                        .WithMany("Likes")
                        .HasForeignKey("KweetId");

                    b.Navigation("Kweet");
                });

            modelBuilder.Entity("Kwetter.Services.KweetService.API.Models.Kweet", b =>
                {
                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
