version: '3'

services:
  kweet-service:
    image: kweetservice:latest
    expose:
      - 8080
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
       MYSQL_DATABASE: kwetter-kweet-service
       MYSQL_ROOT_PASSWORD: test
    ports:
      - "3308:3306"
