version: '3'

services:
  #kweet-service:
  #  image: royappeldoorn/kwetter-kweet-service:latest
  #  expose:
  #    - 8080
  #  environment:
  #  - ConnectionStrings__KweetDatabase=Server=mysql;port=${KWEET_SERVICE_PORT};Database=kwetter-kweet-service;User Id=${KWEET_SERVICE_USER};Password=${KWEET_SERVICE_PASSWORD}
  #  ports:
  #    - "8080:80"
  #  depends_on:
  #    - mysql

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/rabbitmq

  mysql:
    image: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: test
    expose:
      - 3306
    ports:
      - "3308:3306"

volumes:
  rabbitmq:
    driver: local