version: '3'

services:
  kweet-service:
    image: kweetservice:latest
    expose:
      - 8080
    environment:
    - ConnectionStrings__KweetDatabase=Server=mysql;port=${KWEET_SERVICE_PORT};Database=kwetter-kweet-service;User Id=${KWEET_SERVICE_USER};Password=${KWEET_SERVICE_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
       MYSQL_DATABASE: kwetter-kweet-service
       MYSQL_ROOT_PASSWORD: test
    expose:
      - 3306
    ports:
      - "3308:3306"