version: '3'

services:
  kweet-service:
    ports:
      - "80"

  user-service:
    ports:
      - "80"

  follow-service:
    ports:
      - "80"

  authorization-service:
    ports:
      - "80"

  timeline-service:
    ports:
      - "80"