name: .NET

on:
  push:
    branches:
      - main
    paths:
      - src/Services/KweetService/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/Services/KweetService/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install dependencies
      run: dotnet restore ./Services/KweetService/API
      
    - name: Build
      run: dotnet build --no-restore ./Services/KweetService/API
      
    - name: Run tests
      run: dotnet test ./Services/KweetService/Tests
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run tests
      run: dotnet test ./Services/KweetService/Tests
      
  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          allow: network.host
          context: src/
          file: ./src/kwetter-kweet-service.Dockerfile
          platforms: linux/arm/v7,linux/amd64
          push: true
